# Generated by Django 3.2 on 2023-06-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230609_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-id',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='tag',
            name='font_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер шрифта'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('color', 'font_size'), name='unique_color_font_size'),
        ),
    ]
