# Generated by Django 3.2 on 2023-06-13 17:12

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230609_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-id',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='tag',
            name='font_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер шрифта'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиентов не может быть меньше одного'), django.core.validators.MaxValueValidator(32767, 'Количество ингредиентов превышает допустимое значение')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('color', 'font_size'), name='unique_color_font_size'),
        ),
    ]
