# Generated by Django 3.2 on 2023-06-16 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230616_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиентов не может быть меньше одного'), django.core.validators.MaxValueValidator(32767, 'Количество ингредиентов превышает допустимое значение')], verbose_name='Количество'),
        ),
    ]
